import { Category, Product, Review } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-wedding',
    name: 'Wedding Collection',
    slug: 'wedding',
    description: 'Royal groom sherwanis, tuxedos, and opulent wedding suits crafted for unforgettable occasions.',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1600&q=80',
    productCount: 18,
  },
  {
    id: 'cat-shirts',
    name: 'Premium Shirts',
    slug: 'shirts',
    description: 'Egyptian cotton formals, linen casuals, and luxury patterned dress shirts.',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?auto=format&fit=crop&w=1600&q=80',
    productCount: 32,
  },
  {
    id: 'cat-tshirts',
    name: 'T-Shirts',
    slug: 't-shirts',
    description: 'Mercerized cotton polos, relaxed oversized tees, and luxury casual wear.',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1600&q=80',
    productCount: 24,
  },
  {
    id: 'cat-blazers',
    name: 'Blazers & Tuxedos',
    slug: 'blazers',
    description: 'Tailored Italian cut blazers, double-breasted jackets, and party wear tuxedos.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=1600&q=80',
    productCount: 15,
  },
  {
    id: 'cat-sherwani',
    name: 'Sherwani',
    slug: 'sherwani',
    description: 'Regal hand-embroidered zardozi and raw silk groom sherwanis.',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1600&q=80',
    productCount: 12,
  },
  {
    id: 'cat-kurta',
    name: 'Kurta Collection',
    slug: 'kurta',
    description: 'Traditional silk kurtas, Jacquard jackets, and modern festivity outfits.',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1600&q=80',
    productCount: 20,
  },
  {
    id: 'cat-jeans',
    name: 'Jeans & Denim',
    slug: 'jeans',
    description: 'Premium stretch denim, tapered slim fit, and classic vintage wash jeans.',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=1600&q=80',
    productCount: 28,
  },
  {
    id: 'cat-pants',
    name: 'Pants & Chinos',
    slug: 'pants',
    description: 'Sharp formal trousers, breathable cotton chinos, and stretch utility pants.',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=1600&q=80',
    productCount: 22,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Royal Emerald Groom Sherwani with Zardozi Work',
    slug: 'royal-emerald-groom-sherwani',
    description: 'Handcrafted raw silk wedding sherwani in rich emerald green, featuring intricate antique gold zardozi embroidery. Accompanied by a velvet stole and churidar pants. Designed for grooms who appreciate timeless nobility.',
    price: 34999,
    discountPrice: 28999,
    stock: 4,
    material: 'Raw Silk & Velvet Accent',
    isFeatured: true,
    isTrending: true,
    isLimited: true,
    status: 'PUBLISHED',
    categoryId: 'cat-sherwani',
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['M (38)', 'L (40)', 'XL (42)'],
    colors: [{ name: 'Emerald Green', hexCode: '#15803D' }, { name: 'Royale Gold', hexCode: '#D97706' }],
    tags: ['wedding', 'groom', 'sherwani', 'limited'],
  },
  {
    id: 'prod-2',
    name: 'Italian Fit Charcoal Double-Breasted Velvet Tuxedo',
    slug: 'charcoal-double-breasted-tuxedo',
    description: 'Distinguished double-breasted tuxedo jacket crafted from imported Italian wool blend with satin peak lapels. Includes matching tailored trousers for gala nights and wedding receptions.',
    price: 18999,
    discountPrice: 15499,
    stock: 6,
    material: 'Italian Wool & Satin Trim',
    isFeatured: true,
    isTrending: true,
    isLimited: false,
    status: 'PUBLISHED',
    categoryId: 'cat-blazers',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['S (36)', 'M (38)', 'L (40)', 'XL (42)', 'XXL (44)'],
    colors: [{ name: 'Charcoal Black', hexCode: '#111827' }, { name: 'Midnight Navy', hexCode: '#1E3A8A' }],
    tags: ['blazer', 'tuxedo', 'wedding', 'formal'],
  },
  {
    id: 'prod-3',
    name: 'Egyptian Giza Cotton Emerald Executive Shirt',
    slug: 'egyptian-giza-cotton-emerald-shirt',
    description: 'Woven from 100% long-staple Giza cotton, this formal shirt offers a luxurious silk-touch finish with wrinkle-resistant coating. Features cutaway collar and mother-of-pearl buttons.',
    price: 3499,
    discountPrice: 2799,
    stock: 15,
    material: '100% Giza Cotton',
    isFeatured: true,
    isTrending: true,
    isLimited: false,
    status: 'PUBLISHED',
    categoryId: 'cat-shirts',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['39 (M)', '40 (L)', '42 (XL)', '44 (XXL)'],
    colors: [{ name: 'Emerald Green', hexCode: '#22C55E' }, { name: 'Crisp White', hexCode: '#FFFFFF' }],
    tags: ['shirt', 'formal', 'giza cotton'],
  },
  {
    id: 'prod-4',
    name: 'Exclusive Gold Embellished Velvet Bandhgala',
    slug: 'gold-embellished-velvet-bandhgala',
    description: 'Limited production bandhgala jacket crafted in plush midnight velvet with intricate gold bullion crest work on the collar and cuff. Only 5 pieces available in store.',
    price: 24999,
    discountPrice: 21999,
    stock: 3,
    material: 'Plush Micro-Velvet',
    isFeatured: true,
    isTrending: false,
    isLimited: true,
    status: 'PUBLISHED',
    categoryId: 'cat-wedding',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['M (38)', 'L (40)', 'XL (42)'],
    colors: [{ name: 'Midnight Velvet', hexCode: '#0F172A' }, { name: 'Burgundy Wine', hexCode: '#881337' }],
    tags: ['limited', 'bandhgala', 'wedding'],
  },
  {
    id: 'prod-5',
    name: 'Artisan Handloom Chanderi Silk Kurta Set',
    slug: 'chanderi-silk-kurta-set',
    description: 'Breathable hand-loomed Chanderi silk kurta paired with ivory pyjamas. Adorned with delicate thread embroidery along the placket for festive celebrations.',
    price: 6999,
    discountPrice: 5499,
    stock: 12,
    material: 'Chanderi Silk Blend',
    isFeatured: false,
    isTrending: true,
    isLimited: false,
    status: 'PUBLISHED',
    categoryId: 'cat-kurta',
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['S (36)', 'M (38)', 'L (40)', 'XL (42)'],
    colors: [{ name: 'Emerald Cream', hexCode: '#FEF08A' }, { name: 'Royal Sage', hexCode: '#86EFAC' }],
    tags: ['kurta', 'ethnic', 'festive'],
  },
  {
    id: 'prod-6',
    name: 'Mercerized Supima Cotton Luxury Polo T-Shirt',
    slug: 'mercerized-supima-cotton-polo',
    description: 'Signature polo crafted from 100% American Supima cotton with a silk-like mercerized luster. Features a structured collar and custom Fathima emblem tag.',
    price: 2499,
    discountPrice: 1999,
    stock: 20,
    material: '100% Mercerized Supima Cotton',
    isFeatured: false,
    isTrending: true,
    isLimited: false,
    status: 'PUBLISHED',
    categoryId: 'cat-tshirts',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Deep Emerald', hexCode: '#16A34A' }, { name: 'Black Charcoal', hexCode: '#111827' }],
    tags: ['polo', 'tshirt', 'casual'],
  },
  {
    id: 'prod-7',
    name: 'Japanese Selvedge Stretch Tapered Jeans',
    slug: 'japanese-selvedge-stretch-jeans',
    description: 'Premium 13.5oz indigo selvedge denim with 2% elastane flex. Custom brass hardware and hand-distressed detailing.',
    price: 4999,
    discountPrice: 3999,
    stock: 14,
    material: '98% Cotton, 2% Elastane Selvedge',
    isFeatured: true,
    isTrending: false,
    isLimited: false,
    status: 'PUBLISHED',
    categoryId: 'cat-jeans',
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['30', '32', '34', '36', '38'],
    colors: [{ name: 'Vintage Indigo', hexCode: '#1E3A8A' }, { name: 'Washed Black', hexCode: '#374151' }],
    tags: ['jeans', 'denim'],
  },
  {
    id: 'prod-8',
    name: 'Structured Tailored Italian Wool Formal Trouser',
    slug: 'structured-italian-wool-trouser',
    description: 'Flat-front formal trouser designed for maximum comfort and sharp silhouette. Features expandable inner waistband and stain-resistant treatment.',
    price: 3299,
    discountPrice: 2699,
    stock: 18,
    material: '65% Wool, 35% Polyester Blend',
    isFeatured: false,
    isTrending: false,
    isLimited: false,
    status: 'PUBLISHED',
    categoryId: 'cat-pants',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80'
    ],
    sizes: ['30', '32', '34', '36', '38', '40'],
    colors: [{ name: 'Charcoal Grey', hexCode: '#374151' }, { name: 'Navy Blue', hexCode: '#1E3A8A' }],
    tags: ['trousers', 'formal', 'pants'],
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    customerName: 'Mohammed Ashfaq',
    rating: 5,
    comment: 'Selected my wedding sherwani from Fathima Collection. The emerald gold zardozi fit was perfection! Everyone at the reception praised the craftsmanship. Highly recommended in Mangalore.',
    isApproved: true,
    createdAt: '2026-06-15',
  },
  {
    id: 'rev-2',
    customerName: 'Dr. Rahul Shetty',
    rating: 5,
    comment: 'The online order and showroom pickup process was super fast. Reserved 2 Giza cotton shirts online and collected below Malabar Gold within 2 hours. Top notch quality.',
    isApproved: true,
    createdAt: '2026-07-02',
  },
  {
    id: 'rev-3',
    customerName: 'Karthik Rao',
    rating: 5,
    comment: 'Best men\'s clothing showroom on Falnir Road. Their limited edition blazer fitting is unmatched compared to big chain stores. Great customer service!',
    isApproved: true,
    createdAt: '2026-07-10',
  },
];
